#ifndef GAMEHALL_GLOBAL_H
#define GAMEHALL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAMEHALL_LIBRARY)
#  define GAMEHALLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAMEHALLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GAMEHALL_GLOBAL_H
